# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b0d9266c25dc68cda38900165594e1e379f9c6cd2d284f7cd7b2ad1231ca26342afa7b5108965cef09d04b70434262a2eafaa645e4ae15a2cda6c834ce84f88

test:
  secret_key_base: cd00d5f038f4cce73acbf8badc43fff2b9223ea2bd1060e602e1a1eb5d7e8f717028fb5b944708d2a2bf9eb8fdd842ac8732ee389bd9c6f783afacd95e4fe612

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
